name: Build and Publish .NET release assets

env:
  PROJECT_DIR: ./server

permissions:
  contents: write

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Publish Linux
        run: |
          dotnet publish GameInv -p:PublishProfile=FolderProfile-Linux.pubxml

      - name: Publish Windows
        run: |
          dotnet publish GameInv -p:PublishProfile=FolderProfile-Windows.pubxml

      - name: Publish Windows WPF
        run: |
          dotnet publish GameInv-WPF -p:PublishProfile=FolderProfile-Windows.pubxml

      - name: Rename And Move Assets
        run: |
          ORIGINAL_DIR=$(pwd)
          mkdir release_files
          
          mv GameInv/bin/publish/linux-x64/GameInv release_files/GameInv-${{ github.ref_name }}-Linux-x64
          mv GameInv/bin/publish/win-x64/GameInv.exe release_files/GameInv-${{ github.ref_name }}-Windows-x64.exe
          mv GameInv-WPF/bin/publish/win-x64/GameInv-WPF.exe release_files/GameInv-WPF-${{ github.ref_name }}-Windows-x64.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PROJECT_DIR }}/release_files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
